
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pmt
    username: pmt
    password: pmt
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080

management:
  endpoints:
    web.exposure.include: health,info
